name: Auto Comment on PR
â€‹
on:
  pull_request_target:
 Â   types: [ opened, synchronize ]
 Â   branches: [ main ]
â€‹
jobs:
  comment:
 Â   runs-on: ubuntu-latest
â€‹
 Â   steps:
 Â  Â   - name: Checkout code
 Â  Â  Â   uses: actions/checkout@v4
â€‹
 Â  Â   - name: Create a comment
 Â  Â  Â   uses: actions/github-script@v7
 Â  Â  Â   with:
 Â  Â  Â  Â   github-token: ${{ secrets.BOT_TOKEN Â }}
 Â  Â  Â  Â   script: |
 Â  Â  Â  Â  Â   const { owner, repo, number: issue_number } = context.issue;
 Â  Â  Â  Â  Â  Â 
 Â  Â  Â  Â  Â   // Get PR creator's username
 Â  Â  Â  Â  Â   const prCreator = context.payload.pull_request.user.login;
 Â  Â  Â  Â  Â  Â 
 Â  Â  Â  Â  Â   const commentBody = `ðŸš€Thanks for your contribution ðŸŽ‰ @${prCreator}. CodeRabbit(AI) will review your code first ðŸ”¥`;
 Â  Â  Â  Â  Â   github.rest.issues.createComment({
 Â  Â  Â  Â  Â  Â   owner,
 Â  Â  Â  Â  Â  Â   repo,
 Â  Â  Â  Â  Â  Â   issue_number,
 Â  Â  Â  Â  Â  Â   body: commentBody
 Â  Â  Â  Â  Â   });
 Â  Â  Â  Â  Â   github.rest.issues.addLabels({
 Â  Â  Â  Â  Â  Â  Â   owner,
 Â  Â  Â  Â  Â  Â  Â   repo,
 Â  Â  Â  Â  Â  Â  Â   issue_number,
 Â  Â  Â  Â  Â  Â  Â   labels: ['ready to review','waiting-review','Ai ready to review']
 Â  Â  Â  Â  Â  Â   });
